M10: add user authentication and authorisation.
Lucas-Fernandes-Nogueira/DevOps-Course-Starter pull request #10
Opened 2021-05-03 22:33 UTC by Lucas-Fernandes-Nogueira

2021-05-18 11:14 UTC, BenRamchandani requested changes
Hey Lucas,

Can you update your README + .env.template with the new setup steps?

Would also be good to make sure users that aren't in `user_roles.json` can use the app as readers. Not strictly required, but it makes it easier to mark 🙂

2021-05-18 11:14 UTC, BenRamchandani commented on pyproject.toml
> +oauthlib = "^3.1.0"
I don't think you actually use this (which is fine, but you can remove it)

2021-05-18 11:14 UTC, BenRamchandani commented on user.py
> +        return USER_ROLES[self.id] == 'writer'
I suggest you do `USER_ROLES.get(self.id) == 'writer'` here, that way other people can use the app as readers. `dict['key']` throws if `'key'` isn't in `dict`, `dict.get('key')` returns `None`.

Also I don't think `has_reader_role` is used

2021-05-22 19:14 UTC, Lucas-Fernandes-Nogueira commented on user.py
> +        return USER_ROLES[self.id] == 'writer'
Thanks! Just changed it 😁.

2021-05-22 22:15 UTC, Lucas-Fernandes-Nogueira commented
I've done all the markups now 😃.
Regarding "Would also be good to make sure users that aren't in user_roles.json can use the app as readers.", I think it's already doing that. I've tested deleting my GitHub id from user_roles.json and it let me access the app as a reader. Did you mean something else? Do I need to make that more explicit in the code?

2021-05-24 08:14 UTC, BenRamchandani commented
> Regarding "Would also be good to make sure users that aren't in user_roles.json can use the app as readers.", I think it's already doing that. I've tested deleting my GitHub id from user_roles.json and it let me access the app as a reader. Did you mean something else? Do I need to make that more explicit in the code?

That's what the `USER_ROLES[self.id] == 'writer'` -> `return USER_ROLES.get(self.id) == 'writer'` change does. `dict["key"]` throws if the key doesn't exist (the user id is not in USER_ROLES), so the app wasn't useable before if you weren't in the list.

2021-05-24 11:51 UTC, BenRamchandani approved these changes
Looks good to merge.

Let me know once you've resubmitted it on Aptem and I'll accept it.

2021-05-25 09:21 UTC, Lucas-Fernandes-Nogueira commented
> That's what the USER_ROLES[self.id] == 'writer' -> return USER_ROLES.get(self.id) == 'writer' change does. dict["key"] throws if the key doesn't exist (the user id is not in USER_ROLES), so the app wasn't useable before if you weren't in the list.
That's right, sorry for my confusion 😅.

2021-05-26 17:43 UTC, merged